#!/bin/sh

dotnet clean BlabberApp.sln

rm -fr ./BlabberApp.DataStore/obj
rm -fr ./BlabberApp.Console/obj
rm -fr ./BlabberApp.WebApi/obj
rm -fr ./BlabberApp.Client/obj
rm -fr ./BlabberApp.Domain/obj
rm -fr ./BlabberApp.DomainTest/obj
rm -fr ./BlabberApp.DataStoreTest/obj
rm -fr ./BlabberApp.DataStore/bin
rm -fr ./BlabberApp.Console/bin
rm -fr ./BlabberApp.WebApi/bin
rm -fr ./BlabberApp.Client/bin
rm -fr ./BlabberApp.DataStoreTest/bin
